[package]
name = "dlp-svm-tests"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "dlp-svm"
path = "src/main.rs"

[dependencies]
litesvm = "0.16"
dlp-math = { path = "../../crates/math" }
dlp-vault = { path = "../../programs/vault", features = ["no-entrypoint"] }
serde_json = "1"
base64 = "0.22"
solana-address = { version = "2", features = ["curve25519", "decode"] }
solana-account = "4"
solana-instruction = "3"
solana-keypair = "3"
solana-signer = "3"
solana-message = "4"
solana-transaction = "4"
solana-clock = "3"
solana-sysvar-id = "3"
