import {useEffect,useState} from 'react';
import {ArrowRight,ExternalLink,RefreshCw,Wallet} from 'lucide-react';
import type {OrderPlan,TradingAccount} from '../../strategy/execution.js';
import {connectWallet,type Outcome,type TradingClient} from './client.js';

type Symbol='ETH'|'NVDA'|'SPY';
const number=new Intl.NumberFormat('en',{maximumFractionDigits:6});
export function TradingPanel({symbol,side,leverage,collateral}:{symbol:Symbol;side:'long'|'short';leverage:3|5|10;collateral:string}){
  const [client,setClient]=useState<TradingClient|null>(null),[account,setAccount]=useState<TradingAccount|null>(null);
  const [wallet,setWallet]=useState({usdg:'0',eth:'0'}),[fundAmount,setFundAmount]=useState('5');
  const [busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState<Outcome|null>(null),[plan,setPlan]=useState<OrderPlan|null>(null),[clock,setClock]=useState(Date.now());
  const [authorized,setAuthorized]=useState(false);
  useEffect(()=>{setPlan(null);},[symbol,side,leverage,collateral]);
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[]);
  const refresh=async(c=client)=>{if(!c)return;const [a,b]=await Promise.all([c.refresh(),c.balances()]);setAccount(a);setWallet(b);setAuthorized(c.authorized);};
  useEffect(()=>{
    if(!client)return;let active=true;const timer=setInterval(()=>{void Promise.all([client.refresh(),client.balances()]).then(([a,b])=>{if(active){setAccount(a);setWallet(b);}}).catch(()=>{});},15000);
    const provider=client.provider as typeof client.provider&{on?:(event:string,fn:()=>void)=>void;removeListener?:(event:string,fn:()=>void)=>void};
    const changed=()=>{client.authorized=false;setAuthorized(false);setPlan(null);setError('Wallet account or network changed. Reconnect to continue.');};
    provider.on?.('accountsChanged',changed);provider.on?.('chainChanged',changed);
    return()=>{active=false;clearInterval(timer);provider.removeListener?.('accountsChanged',changed);provider.removeListener?.('chainChanged',changed);};
  },[client]);
  async function run(label:string,fn:()=>Promise<void>){if(busy)return;setBusy(label);setError('');try{await fn();}catch(e){setError((e as Error).message||'The request could not be completed.');}finally{setBusy('');}}
  async function connect(){const c=await connectWallet();setClient(c);setAccount(null);setWallet({usdg:'0',eth:'0'});setAuthorized(false);setNotice(null);setPlan(null);await refresh(c);}
  const positions=account?.positions.filter(p=>Number(p.position)>0)??[];
  return <div className="trading-panel">
    {!client?<><button className="wl-button" type="button" disabled={!!busy} onClick={()=>void run('Connecting wallet…',connect)}><Wallet size={18}/>Connect wallet to trade<ArrowRight size={17}/></button><p className="trade-notice">Use a browser wallet or open this page in your mobile wallet. Orders use your own Lighter account on Robinhood Chain. These positions do not mint transferable deltaLP shares.</p></>:<>
      <button type="button" className="inline-link reconnect-wallet" disabled={!!busy} onClick={()=>void run('Reconnecting wallet…',connect)}>Reconnect / change wallet</button><div className="account-summary"><div><strong>{client.address.slice(0,6)}…{client.address.slice(-4)}</strong><button type="button" className="inline-link" disabled={!!busy} onClick={()=>void run('Refreshing balances…',async()=>{await refresh();setNotice(await client.reconcile());})}>Refresh status <RefreshCw size={13}/></button></div><dl><div><dt>Wallet USDG</dt><dd>{number.format(Number(wallet.usdg))}</dd></div><div><dt>Lighter available</dt><dd>{account?number.format(Number(account.available_balance)):'Account not created yet'}</dd></div><div><dt>Gas ETH</dt><dd>{number.format(Number(wallet.eth))}</dd></div></dl></div>
      <details className="funding-panel" open={!account}><summary>Deposit / withdraw USDG</summary><label>Amount (USDG)<input aria-label="Transfer amount in USDG" inputMode="decimal" value={fundAmount} maxLength={14} onChange={event=>setFundAmount(event.target.value)}/></label><div className="funding-actions"><button type="button" className="secondary-button" disabled={!!busy} onClick={()=>void run('Confirm deposit in your wallet…',async()=>{setNotice(await client.deposit(fundAmount));await refresh();})}>Deposit USDG</button><button type="button" className="secondary-button" disabled={!!busy||!authorized||!!positions.length} onClick={()=>void run('Requesting withdrawal…',async()=>{setNotice(await client.withdraw(fundAmount));await refresh();})}>Withdraw USDG</button></div><p className="trade-notice">Deposits go to your Lighter account. Withdrawals return to your wallet after venue settlement. Close positions before withdrawing.</p></details>
      {account&&!authorized?<><button type="button" className="wl-button" disabled={!!busy} onClick={()=>void run('Authorize trading in your wallet…',async()=>{setNotice(await client.authorize());await refresh();})}>Authorize browser trading <ArrowRight size={17}/></button><p className="trade-notice">Your wallet signs a browser trading-key authorization. The key stays in this browser’s memory. Each order still needs your confirmation here.</p></>:null}
      {authorized?<><button type="button" className="wl-button" disabled={!!busy||!!positions.length} onClick={()=>void run('Setting isolated margin and checking the book…',async()=>{setPlan(null);setPlan(await client.prepare({symbol,side,leverage,collateral}));await refresh();})}>Review {leverage}× {side}<ArrowRight size={17}/></button><p className="trade-notice">Sets isolated margin to {leverage}× or lower. Order sizing reserves 1% of your collateral input for fees and rounding.</p><button type="button" className="inline-link revoke-key" disabled={!!busy} onClick={()=>void run('Revoke authorization in your wallet…',async()=>{setNotice(await client.revoke());setAuthorized(false);})}>Revoke this browser’s trading key</button></>:null}
      {positions.length?<section className="positions-list"><h3>Your positions</h3>{positions.map(position=><article key={position.market_id}><strong>{position.sign===1?'Long':'Short'} {position.position} {position.symbol}</strong><span>Unrealized PnL: {position.unrealized_pnl} USDG</span><span>Liquidation price: {position.liquidation_price} USDG</span>{(['ETH','NVDA','SPY'] as string[]).includes(position.symbol)?<button type="button" className="secondary-button" disabled={!!busy||!authorized} onClick={()=>void run('Reviewing reduce-only close…',async()=>{setPlan(await client.prepare({symbol:position.symbol as Symbol,side:'long',leverage:3,collateral:'0'},true));})}>Review close</button>:<a href="https://robinhoodchain.lighter.xyz" target="_blank" rel="noreferrer">Manage this market on Lighter</a>}</article>)}</section>:null}
    </>}
    {plan?<section className="quote-result" aria-label="Order confirmation"><strong>{plan.reduceOnly?'Close position':`${plan.leverage}× ${plan.side}`} · {plan.symbol}</strong><dl><div><dt>Size</dt><dd>{plan.size} {plan.symbol}</dd></div><div><dt>{plan.side==='long'?'Maximum buy price':'Minimum sell price'}</dt><dd>{plan.price} USDG</dd></div><div><dt>Notional at limit</dt><dd>{plan.notional} USDG</dd></div><div><dt>Order</dt><dd>Immediate or cancel{plan.reduceOnly?' · reduce only':''}</dd></div></dl><p className="trade-notice">Leveraged positions can be liquidated. Unfilled quantity cancels immediately; partial fills remain open. {plan.reduceOnly?'This order can only reduce your position.':'This is a directional trade, not a delta-neutral strategy.'}</p><button type="button" className="wl-button" disabled={!!busy||clock>plan.expiresAt} onClick={()=>void run('Submitting and confirming fills…',async()=>{if(!client)return;const selected=plan;setPlan(null);setNotice(await client.trade(selected));await refresh();})}>{clock>plan.expiresAt?'Quote expired — review again':`Confirm ${plan.reduceOnly?'close':plan.side} · ${Math.max(0,Math.ceil((plan.expiresAt-clock)/1000))}s`}</button></section>:null}
    {busy?<p role="status" className="trade-notice"><RefreshCw className="wl-spin" size={14}/> {busy}</p>:null}
    {notice?<div className="execution-status" role="status"><strong>{notice.message}</strong>{notice.hash?<code>{notice.hash}</code>:null}{notice.state==='pending'||notice.state==='unknown'||notice.state==='needs-review'?<button type="button" className="secondary-button" disabled={!!busy} onClick={()=>void run('Reconciling transaction…',async()=>{if(client){setNotice(await client.reconcile());await refresh();}})}>Refresh confirmation</button>:null}</div>:null}
    {error?<p className="wl-error" role="alert">{error}</p>:null}
    <p className="trade-notice">New integration: a funded mainnet deposit, trade, close, and withdrawal has not yet been verified end to end.</p>
    <a className="inline-link venue-recovery" href="https://robinhoodchain.lighter.xyz" target="_blank" rel="noreferrer">Manage orders and recovery on Lighter <ExternalLink size={14}/></a>
  </div>;
}
