import {useEffect,useState,lazy,Suspense} from 'react';
import {ArrowRight,ArrowUpRight,ExternalLink} from 'lucide-react';
import type {Market} from '../strategy/lighter.ts';
const TradingPanel=lazy(()=>import('./trading/TradingPanel.js').then(module=>({default:module.TradingPanel})));

const source='https://github.com/staccDOTsol/delta-LP';
const explorer='https://robin.etherscan.io/address/0x32C47683D0E41DAc58A750fccb7200ad031D3993#code';
const number=new Intl.NumberFormat('en',{maximumFractionDigits:2});
type Vault={depositsEnabled:boolean;totalShares:string;borrowAvailableNvda:string;liquidity:string;block:string};
async function api<T>(path:string,body?:unknown):Promise<T>{const response=await fetch(`/api/strategies/${path}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const value=await response.json();if(!response.ok)throw new Error(value.error??'Please try again.');return value;}

export function Strategies(){
  const [markets,setMarkets]=useState<Market[]>([]),[vault,setVault]=useState<Vault|null>(null),[error,setError]=useState(''),[vaultError,setVaultError]=useState('');
  const [symbol,setSymbol]=useState<'ETH'|'NVDA'|'SPY'>('ETH'),[side,setSide]=useState<'neutral'|'long'|'short'>('long');
  const [leverage,setLeverage]=useState<3|5|10>(3),[collateral,setCollateral]=useState('5');
  useEffect(()=>{let active=true;const refresh=()=>{
    void api<{markets:Market[]}>('markets').then(value=>{if(active){setMarkets(value.markets);setError('');}}).catch(()=>{if(active){setMarkets([]);setError('Live prices unavailable. Try again shortly.');}});
    void api<Vault>('vault').then(value=>{if(active){setVault(value);setVaultError('');}}).catch(()=>{if(active){setVault(null);setVaultError('Vault status unavailable.');}});
  };refresh();const interval=setInterval(refresh,15000);return()=>{active=false;clearInterval(interval);};},[]);
  return <div className="wl-shell strategy-shell"><header className="wl-header wrap"><a className="wl-brand" href="/" aria-label="deltaLP home"><span className="wl-mark">△</span>delta<span>LP</span></a><nav aria-label="Main navigation"><a href="/oil">Oil subscriptions <ArrowUpRight size={15}/></a><a href={source} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a></nav></header>
    <main className="wrap strategy-main"><div className="strategy-intro"><div><span className="wl-kicker"><span className="status-dot"/> ROBINHOOD CHAIN · MAINNET 4663</span><h1>Pick your exposure.</h1><p>Long and short perpetuals through your wallet.<br/>Tokenized strategies are still in development.</p></div><a className="inline-link" href="/oil">Oil & gas subscription waitlist <ArrowUpRight size={17}/></a></div>
      <div className="strategy-grid"><section className="strategy-terminal" aria-label="Strategy selection"><div className="strategy-tabs" role="group" aria-label="Strategy"><button aria-pressed={side==='neutral'} onClick={()=>setSide('neutral')}>Delta neutral</button><button aria-pressed={side==='long'} onClick={()=>setSide('long')}>Long</button><button aria-pressed={side==='short'} onClick={()=>setSide('short')}>Short</button></div>
        {side==='neutral'?<div className="neutral-panel"><span className="track-label">HEDGED LIQUIDITY</span><h2>A long LP.<br/>A matched short.</h2><p>The LP supplies liquidity. The short offsets its changing base-asset exposure. Fees, funding, slippage, and rebalancing determine the result.</p><div className="readiness-box"><strong>NVDA / USDG · Morpho vault</strong><span>{vault ? (vault.depositsEnabled?'Deposits enabled on-chain':'Deposits closed on-chain') : 'Reading mainnet…'}</span><dl><div><dt>Borrow liquidity</dt><dd>{vault?`${number.format(Number(vault.borrowAvailableNvda))} NVDA`:'—'}</dd></div><div><dt>Receipt supply</dt><dd>{vault?number.format(Number(vault.totalShares)):'—'}</dd></div><div><dt>LP position</dt><dd>{vault?(vault.liquidity==='0'?'Empty':'Funded'):'—'}</dd></div></dl><a className="inline-link" href={explorer} target="_blank" rel="noreferrer">Inspect deployed contract <ExternalLink size={14}/></a>{vaultError?<p role="alert">{vaultError}</p>:null}</div><div className="route-note"><strong>Next route: ETH LP + Lighter perpetual short</strong><p>Live perpetual liquidity removes the stock-borrow dependency. The perpetual order adapter is implemented. Connecting LP inventory, hedge rebalancing, and receipt accounting remains unfinished; this vault cannot accept deposits.</p></div></div>:<div className="trade-form"><div className="trade-label"><span className="track-label">{side==='long'?'LONG':'SHORT'} · LIGHTER ROBINHOOD</span><span className="state-pill">Direct perpetuals</span></div><label>Market<select value={symbol} onChange={event=>setSymbol(event.target.value as typeof symbol)}><option>ETH</option><option>NVDA</option><option>SPY</option></select></label><fieldset><legend>Leverage</legend><div className="leverage-options">{([3,5,10] as const).map(value=><button type="button" key={value} aria-pressed={leverage===value} onClick={()=>setLeverage(value)}>{value}×</button>)}</div></fieldset><label>Collateral budget <span>USDG</span><input inputMode="decimal" value={collateral} onChange={event=>setCollateral(event.target.value)} maxLength={14} required/></label><Suspense fallback={<p role="status">Loading wallet controls…</p>}><TradingPanel symbol={symbol} side={side} leverage={leverage} collateral={collateral}/></Suspense></div>}
        {error?<p className="wl-error" role="alert">{error}</p>:null}</section>
        <aside className="market-panel"><span className="wl-kicker">LIVE VENUE SNAPSHOT</span><h2>Liquidity comes first.</h2><p>Current Lighter Robinhood order books. Depth shown within 0.1% of the midpoint, from up to 100 displayed levels per side.</p><div className="market-rows">{markets.length?markets.map(value=><article key={value.symbol}><header><strong>{value.symbol}</strong><span>{number.format(Number(value.mark))} USDG</span></header><dl><div><dt>Bid / ask</dt><dd>{value.bid} / {value.ask}</dd></div><div><dt>Bid depth</dt><dd>${number.format(value.bidDepth10bps)}</dd></div><div><dt>Ask depth</dt><dd>${number.format(value.askDepth10bps)}</dd></div></dl><small>{value.active?'Venue market active':'Venue market unavailable'} · observed {new Date(value.observedAt).toLocaleTimeString()}</small></article>):<p role="status">{error?'Market data unavailable.':'Loading live order books…'}</p>}</div><a className="inline-link" href="https://docs.robinhood.com/chain/lighter-domains/" target="_blank" rel="noreferrer">Venue and custody details <ExternalLink size={14}/></a></aside>
      </div><section className="oil-banner"><div><span className="wl-kicker">OIL & GAS SUBSCRIPTIONS</span><h2>Plan the next winter.</h2><p>Heating oil, propane, or natural gas. Tell us your region and join the subscription waitlist.</p></div><a className="wl-button" href="/oil">Join the oil waitlist <ArrowRight size={18}/></a></section>
    </main><footer className="wl-footer wrap"><p>Independent project. Not affiliated with Robinhood or Lighter.</p><a href="/oil">Oil subscription waitlist</a></footer></div>;
}
