import {useEffect,useState,lazy,Suspense} from 'react';
import {ArrowRight,ArrowUpRight,ExternalLink} from 'lucide-react';
import type {Market} from '../strategy/lighter.ts';
import type {TokenizedStatus} from '../strategy/tokenized.ts';
import {pairedLeverageIllustration} from '../strategy/member-pairs.ts';
import {NftEditions} from './NftEditions.tsx';
const TradingPanel=lazy(()=>import('./trading/TradingPanel.js').then(module=>({default:module.TradingPanel})));
const NeutralPanel=lazy(()=>import('./trading/NeutralPanel.js').then(module=>({default:module.NeutralPanel})));

const source='https://github.com/staccDOTsol/delta-LP';
const design=`${source}/blob/codex/fuel-platform/docs/TOKENIZED-MEMBERS.md`;
const fanout='https://robin.etherscan.io/address/0x1b88A6c6516FD2918905186F21Bb9F5CaA1a15c8#code';
const explorer='https://robin.etherscan.io/address/0x32C47683D0E41DAc58A750fccb7200ad031D3993#code';
const number=new Intl.NumberFormat('en',{maximumFractionDigits:2});
type Vault={depositsEnabled:boolean;totalShares:string;borrowAvailableNvda:string;liquidity:string;block:string};
async function api<T>(path:string,body?:unknown):Promise<T>{const response=await fetch(`/api/strategies/${path}`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const value=await response.json();if(!response.ok)throw new Error(value.error??'Please try again.');return value;}

export function Strategies(){
  const [markets,setMarkets]=useState<Market[]>([]),[vault,setVault]=useState<Vault|null>(null),[error,setError]=useState(''),[vaultError,setVaultError]=useState('');
  const [tokenized,setTokenized]=useState<TokenizedStatus|null>(null),[tokenizedError,setTokenizedError]=useState('');
  const [symbol,setSymbol]=useState<'ETH'|'NVDA'|'SPY'>('ETH'),[side,setSide]=useState<'neutral'|'long'|'short'>('neutral');
  const [leverage,setLeverage]=useState<3|5|10>(3),[collateral,setCollateral]=useState('5');
  useEffect(()=>{let active=true;const refresh=()=>{
    void api<{markets:Market[]}>('markets').then(value=>{if(active){setMarkets(value.markets);setError('');}}).catch(()=>{if(active){setMarkets([]);setError('Live prices unavailable. Try again shortly.');}});
    void api<TokenizedStatus>('tokenized').then(value=>{if(active){setTokenized(value);setTokenizedError('');}}).catch(()=>{if(active){setTokenized(null);setTokenizedError('Contract status unavailable.');}});
    void api<Vault>('vault').then(value=>{if(active){setVault(value);setVaultError('');}}).catch(()=>{if(active){setVault(null);setVaultError('Vault status unavailable.');}});
  };refresh();const interval=setInterval(refresh,15000);return()=>{active=false;clearInterval(interval);};},[]);
  return <div className="wl-shell strategy-shell"><header className="wl-header wrap"><a className="wl-brand" href="/" aria-label="deltaLP home"><span className="wl-mark">△</span>delta<span>LP</span></a><nav aria-label="Main navigation"><a href="/oil">Oil subscriptions <ArrowUpRight size={15}/></a><a href={source} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a></nav></header>
    <main className="wrap strategy-main"><div className="strategy-intro"><div><span className="wl-kicker"><span className="status-dot"/> ROBINHOOD CHAIN · MAINNET 4663</span><h1>A market for every<br/>side of the trade.</h1><p>Tokenized longs and shorts. Markets against each other and majors.<br/>One coordinated family per underlying.</p><span className="development-label">Tokenized core deployed · account setup and strategy integration in progress</span></div><a className="inline-link" href="/oil">Oil & gas subscription waitlist <ArrowUpRight size={17}/></a></div>
      <div className="strategy-grid"><section className="strategy-terminal" aria-label="Strategy selection"><div className="strategy-tabs" role="group" aria-label="Strategy"><button aria-pressed={side==='neutral'} onClick={()=>setSide('neutral')}>Delta neutral</button><button aria-pressed={side==='long'} onClick={()=>setSide('long')}>Long</button><button aria-pressed={side==='short'} onClick={()=>setSide('short')}>Short</button></div>
        {side==='neutral'?<div className="neutral-panel">
          <Suspense fallback={<p role="status">Loading neutral pool controls…</p>}><NeutralPanel/></Suspense>
          <a className="inline-link" href={design} target="_blank" rel="noreferrer">Read the design and test coverage <ExternalLink size={14}/></a>
          <details className="legacy-vault member-deployment"><summary>Deployed tokenized contracts</summary><div className="readiness-box"><strong>Robinhood Chain · contract status</strong><p>{tokenized?`Code checked at block ${tokenized.block}. ${tokenized.memberCount} member strategies registered.`:tokenizedError||'Checking deployed bytecode…'}</p><p>Receipts represent actual paired V4 liquidity. Pending cash and unactivated member claims remain separate. Live venue setup and confirmed fills are required before activation.</p>{tokenized?.contracts.map(contract=><a key={contract.name} className="inline-link" href={contract.explorer} target="_blank" rel="noreferrer">{({MemberController:'Controller',MemberFactory:'Member factory',MemberV4Hook:'V4 activity hook',HouseFeeRouter:'House fee router',WeightedNftFeeFanout:'NFT fee distributor',NeutralVault:'DN receipt vault',NeutralEscrowFactory:'Allocation / exit escrows'} as Record<string,string>)[contract.name]} <span>{contract.address.slice(0,8)}…{contract.address.slice(-4)}</span><ExternalLink size={14}/></a>)}</div></details>
          <details className="legacy-vault"><summary>Earlier NVDA / Morpho vault</summary><div className="readiness-box"><strong>NVDA / USDG · separate deployment</strong><span>{vault ? (vault.depositsEnabled?'Deposits enabled on-chain':'Deposits closed on-chain') : 'Reading mainnet…'}</span><dl><div><dt>Borrow liquidity</dt><dd>{vault?`${number.format(Number(vault.borrowAvailableNvda))} NVDA`:'—'}</dd></div><div><dt>Receipt supply</dt><dd>{vault?number.format(Number(vault.totalShares)):'—'}</dd></div><div><dt>LP position</dt><dd>{vault?(vault.liquidity==='0'?'Empty':'Funded'):'—'}</dd></div></dl><a className="inline-link" href={explorer} target="_blank" rel="noreferrer">Inspect earlier contract <ExternalLink size={14}/></a>{vaultError?<p role="alert">{vaultError}</p>:null}</div></details>
        </div>:<div className="trade-form"><div className="trade-label"><span className="track-label">{side==='long'?'LONG':'SHORT'} · LIGHTER ROBINHOOD</span><span className="state-pill">Direct perpetuals</span></div><p className="direct-route-note">This trades in your own Lighter account. It does not mint a member token; member mint and redeem fees do not apply here.</p><label>Market<select value={symbol} onChange={event=>setSymbol(event.target.value as typeof symbol)}><option>ETH</option><option>NVDA</option><option>SPY</option></select></label><fieldset><legend>Leverage</legend><div className="leverage-options">{([3,5,10] as const).map(value=><button type="button" key={value} aria-pressed={leverage===value} onClick={()=>setLeverage(value)}>{value}×</button>)}</div></fieldset><label>Collateral budget <span>USDG</span><input inputMode="decimal" value={collateral} onChange={event=>setCollateral(event.target.value)} maxLength={14} required/></label><Suspense fallback={<p role="status">Loading wallet controls…</p>}><TradingPanel symbol={symbol} side={side} leverage={leverage} collateral={collateral}/></Suspense></div>}
        {error?<p className="wl-error" role="alert">{error}</p>:null}</section>
        <aside className="market-panel"><span className="wl-kicker">LIVE VENUE SNAPSHOT</span><h2>Liquidity comes first.</h2><p>Current Lighter Robinhood order books. Depth shown within 0.1% of the midpoint, from up to 100 displayed levels per side.</p><div className="market-rows">{markets.length?markets.map(value=><article key={value.symbol}><header><strong>{value.symbol}</strong><span>{number.format(Number(value.mark))} USDG</span></header><dl><div><dt>Bid / ask</dt><dd>{value.bid} / {value.ask}</dd></div><div><dt>Bid depth</dt><dd>${number.format(value.bidDepth10bps)}</dd></div><div><dt>Ask depth</dt><dd>${number.format(value.askDepth10bps)}</dd></div></dl><small>{value.active?'Venue market active':'Venue market unavailable'} · observed {new Date(value.observedAt).toLocaleTimeString()}</small></article>):<p role="status">{error?'Market data unavailable.':'Loading live order books…'}</p>}</div><a className="inline-link" href="https://docs.robinhood.com/chain/lighter-domains/" target="_blank" rel="noreferrer">Venue and custody details <ExternalLink size={14}/></a></aside>
      </div>
      <section className="member-economics" aria-labelledby="economics-title"><div className="economics-heading"><div><span className="wl-kicker">THE TOKENIZED DESIGN</span><h2 id="economics-title">Different roles. A shared market.</h2></div><span className="state-pill">Not yet accepting tokenized deposits</span></div>
        <div className="participant-grid"><article><span className="participant-number">01</span><h3>Traders & hedgers</h3><p>Choose an underlying, direction, and leverage. Combine opposing exposures or trade member tokens against majors through V4 pools.</p></article><article><span className="participant-number">02</span><h3>LPs & arbitrageurs</h3><p>LPs collect pool swap fees. Arbitrageurs trade price differences. Ordinary member transfers carry no house tax, and pools choose their own swap fees.</p></article><article><span className="participant-number">03</span><h3>Wizards & NFT holders</h3><p>The 3%/6% fee policy shares house fees equally between the 8,010 Wizards and 40,000 NFTs across four collections. NFT shares are weighted by mint tier.</p><a className="inline-link" href={fanout} target="_blank" rel="noreferrer">Inspect the fee recipient <ExternalLink size={14}/></a></article></div>
        <div className="fee-policy"><div className="fee-tile"><strong>3%</strong><span>Member mint fee</span></div><div className="fee-tile"><strong>6%</strong><span>Member redeem fee</span></div><div className="fee-tile"><strong>0%</strong><span>Transfer tax</span></div><div className="fee-example"><strong>Half to Wizards. Half to NFT holders.</strong><p>The replacement contracts split house fees 50/50 between Homecoming’s 8,010 Wizards and four collections of 10,000 NFTs, weighted by their $1 / $2 / $5 / $10 mint tiers. At unchanged NAV, 100 USDG → 97 USDG backing → 91.18 USDG out; each group receives 4.41 USDG. Swap fees and trading costs are separate.</p><p>{tokenized?tokenized.nftFeeShareBps===5000?`Verified deployed policy: ${tokenized.entryFeeBps/100}% entry / ${tokenized.exitFeeBps/100}% exit, split 50/50 between Wizards and the NFT distributor.`:`Current deployed contracts still charge ${tokenized.entryFeeBps/100}% entry / ${tokenized.exitFeeBps/100}% exit to Wizards. The new fee contracts are not active yet.`:'Reading the current deployed fee policy…'}</p></div></div>
        <LeverageHypothesis/>
        <div className="economics-note"><h3>Fee income, with an explicit hedge.</h3><p>Delta neutrality aims to reduce directional exposure. Equal opposing perpetual positions also offset their funding; they do not create free yield. Swap fees must exceed inventory losses, execution costs, and hedge costs. No APY has been established, and leveraged positions can still be liquidated.</p></div>
      </section>
      <NftEditions/>
      <section className="oil-banner"><div><span className="wl-kicker">OIL & GAS SUBSCRIPTIONS</span><h2>Plan the next winter.</h2><p>Heating oil, propane, or natural gas. Tell us your region and join the subscription waitlist.</p></div><a className="wl-button" href="/oil">Join the oil waitlist <ArrowRight size={18}/></a></section>
    </main><footer className="wl-footer wrap"><p>Independent project. Not affiliated with Robinhood or Lighter.</p><a href="/oil">Oil subscription waitlist</a></footer></div>;
}

function LeverageHypothesis(){
  const [move,setMove]=useState(1);
  return <section className="leverage-hypothesis" aria-labelledby="hypothesis-title"><div><span className="wl-kicker">THE VOLUME HYPOTHESIS</span><h3 id="hypothesis-title">Small underlying move.<br/>Much bigger relative move.</h3><p>A matched long/short pair amplifies movement between its two token prices. That may create more repricing and fee-paying opportunities per dollar of liquidity. The same amplification increases inventory risk.</p><label htmlFor="underlying-move">Illustrative underlying move <output htmlFor="underlying-move">+{move.toFixed(1)}%</output></label><input id="underlying-move" type="range" min="0.1" max="5" step="0.1" value={move} onChange={event=>setMove(Number(event.target.value))}/></div><div className="hypothesis-results"><table><caption>Equal starting backing · one upward price move</caption><thead><tr><th scope="col">Pair</th><th scope="col">Pair-price move</th><th scope="col">Baseline pool loss*</th></tr></thead><tbody>{[3,5,10].map(leverage=>{const result=pairedLeverageIllustration(leverage,move);return <tr key={leverage}><th scope="row">{leverage}× / {leverage}×</th><td>+{result.relativePriceChangePct.toFixed(2)}%</td><td>{result.feeFreePoolLossPct.toFixed(3)}%</td></tr>;})}</tbody></table><p>*Ordinary full-range constant-product pool after repricing, without fees, leverage resets, or the planned controller adjustments. Concentrated V4 positions differ. This baseline is not a forecast of our strategy’s returns.</p></div></section>;
}
