import { useEffect, useRef, useState, type FormEvent } from 'react';
import {OpenSeaNav,OpenSeaHero} from './OpenSeaLinks.tsx';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Copy, ExternalLink, Layers3, LoaderCircle, Mail, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import type { MemberStatus } from '../waitlist/store.ts';
import type { Preference } from '../waitlist/preferences.ts';
import { Preferences, preferenceLabel } from './Preferences.tsx';

const source = 'https://github.com/staccDOTsol/delta-LP';
async function request<T>(path: string, body?: unknown): Promise<T> {
  const response = await fetch(`/api/waitlist/${path}`, { method:body === undefined ? 'GET':'POST', headers:body === undefined ? {} : {'Content-Type':'application/json'}, body:body === undefined ? undefined : JSON.stringify(body) });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error ?? 'Please try again in a moment.');
  return result;
}
const nf = new Intl.NumberFormat('en');

export function Waitlist() {
  const [member,setMember] = useState<MemberStatus | null>(null);
  const [count,setCount] = useState<number | null>(null), [loading,setLoading] = useState(true);
  const [email,setEmail] = useState(''), [sent,setSent] = useState(false), [busy,setBusy] = useState(false), [error,setError] = useState('');
  const [signingIn,setSigningIn] = useState(false);
  const [preference,setPreference] = useState<Preference>({product:'oil-subscription',fuel:'heating-oil',region:''}), [editPreference,setEditPreference] = useState(false), [preferenceSaved,setPreferenceSaved] = useState(false);
  const [copied,setCopied] = useState(false), [privacy,setPrivacy] = useState(false), [deleteOpen,setDeleteOpen] = useState(false);
  const [verifyToken,setVerifyToken] = useState(() => new URLSearchParams(location.hash.slice(1)).get('verify'));
  const [referral] = useState(() => {
    const value = new URLSearchParams(location.search).get('ref');
    if (value && /^[A-Za-z0-9_-]{12}$/.test(value)) { try { sessionStorage.setItem('delta-ref',value); } catch {} return value; }
    try { return sessionStorage.getItem('delta-ref') ?? ''; } catch { return ''; }
  });
  const dialog = useRef<HTMLDialogElement>(null);
  async function refresh() {
    const [me,stats] = await Promise.all([request<{member:MemberStatus | null}>('me'),request<{verified:number}>('stats')]);
    setMember(me.member); setCount(stats.verified);
  }
  useEffect(() => { let active=true; refresh().catch(() => { if(active) setError('We could not load the waitlist. Please refresh or try again shortly.'); }).finally(() => { if(active) setLoading(false); }); return () => { active=false; }; }, []);
  useEffect(() => { if (!member) return; const timer = setInterval(() => { void refresh().catch(() => {}); },30_000); return () => clearInterval(timer); },[member?.code]);
  useEffect(() => { if (privacy || deleteOpen) dialog.current?.showModal(); else dialog.current?.close(); },[privacy,deleteOpen]);
  useEffect(() => { if (!copied) return; const timer=setTimeout(() => setCopied(false),2500); return () => clearTimeout(timer); },[copied]);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError('');
    try { await request('join',{email,...(!signingIn ? {preference}:{}),consent:form.get('consent') === 'on',...(referral ? {referral}:{}),website:form.get('website') ?? ''}); setSent(true); }
    catch(e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function verify() {
    if (!verifyToken) return; setBusy(true);setError('');
    try { const value=await request<{member:MemberStatus}>('verify',{token:verifyToken}); setMember(value.member);setCount(value.member.total);setVerifyToken(null);history.replaceState(null,'','/oil'); }
    catch(e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function savePreference(event:FormEvent<HTMLFormElement>) { event.preventDefault();setBusy(true);setError('');try { const value=await request<{member:MemberStatus}>('preference',preference);setMember(value.member);setEditPreference(false);setPreferenceSaved(true); }catch(e){setError((e as Error).message);}finally{setBusy(false);} }
  async function logout() { setBusy(true);setError('');try { await request('logout',{});setMember(null);setSent(false);setEmail(''); } catch(e) {setError((e as Error).message);}finally{setBusy(false);} }
  async function remove() { setBusy(true);setError('');try {await request('delete',{});setMember(null);setSent(false);setEmail('');setDeleteOpen(false);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);} }
  const referralUrl = member ? `${location.origin}/oil?ref=${member.code}` : '';
  async function copy() { try { await navigator.clipboard.writeText(referralUrl);setCopied(true); } catch { setError('Copy is unavailable in this browser. Select and copy your link below.'); } }
  async function share() { if(navigator.share) { try { await navigator.share({title:'Get early access to deltaLP',text:'Plan the next winter. Join me on the deltaLP oil & gas subscription waitlist.',url:referralUrl}); } catch(e) { if ((e as Error).name !== 'AbortError') setError('Sharing failed. You can copy your referral link instead.'); } } else await copy(); }
  const nextMilestone = member && member.points >= 250 ? 600 : 250;
  return <div className="wl-shell">
    <a href="#signup" className="skip-link">Skip to waitlist</a>
    <header className="wl-header wrap"><a href="/" className="wl-brand" aria-label="deltaLP home"><span className="wl-mark">△</span>delta<span>LP</span></a><nav aria-label="Main navigation"><a className="nav-about" href="#how-it-works">How it works</a><a href={source} target="_blank" rel="noreferrer">The build <ArrowUpRight size={15}/></a><OpenSeaNav/><a className="nav-sister" href="https://staccpad.fun" target="_blank" rel="noreferrer">staccpad.fun <ArrowUpRight size={15}/></a><a href="#signup" className="nav-join">{member ? 'Your place' : 'Join the waitlist'}<ArrowRight size={15}/></a></nav></header>
    <main>
      <section className="hero wrap" aria-labelledby="hero-title">
        <div className="hero-copy"><div className="wl-kicker"><span className="status-dot"/> OIL & GAS · SUBSCRIPTION WAITLIST</div><h1 id="hero-title">Warm homes.<br/>Steady plans.<br/><em>Be early.</em></h1><p className="hero-description">Heating oil, propane, or natural gas.<br className="desktop-break"/> Plan for the season ahead.</p><p className="hero-secondary">Help shape the subscription pilot for colder regions. Tell us your fuel and location. Get a real place in line, and move up with verified referrals.</p><OpenSeaHero/><div className="hero-foot"><span className="circle-arrow"><ArrowDown size={18}/></span><span>Plan your exposure.<br/><strong>Get ahead of the season.</strong></span></div></div>
        <section className={`join-card ${member ? 'member-card' : ''}`} id="signup" aria-label="Waitlist signup and position">
          <div className="card-eyebrow"><span>{member ? 'YOUR EARLY ACCESS PASS' : 'THE NEXT CHAPTER STARTS HERE'}</span><Sparkles size={18}/></div>
          {loading ? <div className="card-loading" role="status"><LoaderCircle className="wl-spin"/>Loading the waitlist…</div> : verifyToken ? <div className="confirmation"><span className="large-icon"><Mail/></span><h2>Your place is one<br/>click away.</h2><p>Confirm your email to activate your points and open your personal waitlist pass.</p><button className="wl-button" onClick={() => void verify()} disabled={busy}>{busy ? <LoaderCircle className="wl-spin" size={18}/> : <Check size={18}/>}Confirm my email</button><button className="plain-button" disabled={busy} onClick={() => {setVerifyToken(null);history.replaceState(null,'','/oil');setError('');}}>Request a new link</button></div> : member ? <>
            <div className="pass-heading"><div><h2>You're on the list.</h2><p className="member-email">{member.email}</p></div><span className="tier-badge">{member.tier}</span></div>
            <section className="saved-preference" aria-label="Saved interests"><span>YOUR INTEREST</span><strong>{preferenceLabel(member.preference)}</strong><button className="plain-button" type="button" onClick={()=>{setPreference(member.preference?.product === 'oil-subscription' ? member.preference : {product:'oil-subscription',fuel:'heating-oil',region:''});setEditPreference(!editPreference);setPreferenceSaved(false);}}>{editPreference ? 'Cancel editing' : 'Edit interests'}</button>{editPreference ? <form onSubmit={savePreference}><Preferences value={preference} onChange={setPreference} oilOnly/><button className="wl-button" disabled={busy} type="submit">{busy ? 'Saving…' : 'Save my interests'}</button></form> : null}<p role="status">{preferenceSaved ? 'Saved to your account. Your points and position stay intact.' : 'Preferences only. No trade or subscription is placed.'}</p></section><div className="pass-metrics"><div><span>YOUR POSITION</span><strong>#{nf.format(member.position)}</strong><small>of {nf.format(member.total)} verified</small></div><div><span>YOUR POINTS</span><strong>{nf.format(member.points)}</strong><small>{member.referrals} confirmed referral{member.referrals === 1 ? '' : 's'}</small></div></div>
            <div className="milestone"><div><span>{member.points >= 600 ? 'Early circle reached' : `Next: ${nextMilestone === 250 ? 'Priority' : 'Early circle'}`}</span><strong>{Math.min(member.points,nextMilestone)} / {nextMilestone} pts</strong></div><progress value={Math.min(member.points,nextMilestone)} max={nextMilestone}/></div>
            <h3>Good company moves you up.</h3><p className="small-copy">Earn <strong>50 points</strong> when someone joins with your link and verifies their email.</p><label className="referral-label" htmlFor="referral-link">Your personal referral link</label><div className="referral-copy"><input id="referral-link" value={referralUrl} readOnly onFocus={e => e.currentTarget.select()}/><button aria-label="Copy referral link" onClick={() => void copy()}>{copied ? <Check size={20}/> : <Copy size={20}/>}</button></div><button className="wl-button" onClick={() => void share()}>Share your invite <ArrowUpRight size={18}/></button><div role="status" className="copy-status">{copied ? 'Referral link copied.' : 'Your rank updates as verified signups arrive.'}</div>
            <details className="activity-details"><summary>Points activity</summary><ul>{member.activity.map((item,i) => <li key={`${item.createdAt}-${i}`}><span>{item.kind === 'email_verified' ? 'Email verified' : 'Referral verified'}<small>{new Date(item.createdAt).toLocaleDateString()}</small></span><strong>+{item.points}</strong></li>)}</ul></details><div className="account-actions"><button onClick={() => void logout()} disabled={busy}>Sign out</button><button onClick={() => setDeleteOpen(true)}>Leave waitlist</button></div>
          </> : sent ? <div className="confirmation"><span className="large-icon"><Mail/></span><h2>Check your inbox.</h2><p>We sent a confirmation link to <strong className="email-wrap">{email}</strong>. Verify your email to activate your place and earn your first 100 points.</p><div className="email-note">The link expires in 20 minutes. Check spam or promotions if you don't see it.</div><button className="wl-button" onClick={() => {setSent(false);setError('');}}>Use another email or resend <ArrowRight size={18}/></button></div> : <>
            <h2>{signingIn ? 'Welcome back.' : <>Get in on the<br/>ground floor.</>}</h2><p>{signingIn ? 'Use your original email to recover your pass, saved interests, and points.' : 'Tell us your fuel needs. Confirm your email. Get your place and a personal referral link.'}</p>{referral ? <div className="referral-notice"><Users size={16}/>You're joining through a community invite.</div> : null}
            <form onSubmit={submit}>{!signingIn ? <Preferences value={preference} onChange={setPreference} oilOnly/> : null}<label htmlFor="waitlist-email">Email address</label><input id="waitlist-email" name="email" type="email" inputMode="email" autoComplete="email" autoCapitalize="none" spellCheck={false} placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} required/><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="consent"><input type="checkbox" name="consent" required/><span>I agree to join the waitlist and receive deltaLP access updates. <button type="button" onClick={() => setPrivacy(true)}>Privacy details</button></span></label><button className="wl-button" type="submit" disabled={busy}>{busy ? <><LoaderCircle size={18} className="wl-spin"/>Sending your link…</> : <>{signingIn ? 'Send sign-in link' : 'Reserve my place'}<ArrowRight size={18}/></>}</button></form><div className="card-assurance"><ShieldCheck size={15}/><span>Free to join. No wallet or deposit needed.</span></div><div className="card-rule"/><div className="join-rewards"><span className="reward-icon"><Sparkles size={18}/></span><div><strong>Your first 100 points</strong><span>Confirm your email. Start moving up.</span></div><span className="plus-points">+100</span></div><p className="returning"><button type="button" onClick={()=>{setSigningIn(!signingIn);setError('');}}>{signingIn ? 'New here? Join the waitlist' : 'Already joined? Sign in to your pass'}</button></p>
          </>}
          {error ? <div className="wl-error" role="alert">{error}</div> : null}
        </section>
      </section>
      <div className="chain-strip"><div className="wrap"><span><span className="status-dot"/>{count === null ? 'Live waitlist' : `${nf.format(count)} verified ${count === 1 ? 'member' : 'members'}`}</span><span>Oil & gas subscription pilot</span><a href="/">Explore mainnet strategies <ArrowUpRight size={15}/></a></div></div>
      <section className="launch-tracks wrap"><div className="section-heading"><div><span className="wl-kicker">PLAN THE SEASON AHEAD</span><h2>Make winter<br/>part of the plan.</h2></div><p>Tell us where you need service.<br/>Help shape the first pilot regions.</p></div><div className="oil-pilot-notes"><p>We are developing a seasonal subscription for heating oil, propane, and natural gas: planned budgets, supplier coverage, and fuel needs coordinated before the cold arrives.</p><p>Pricing, supplier agreements, service areas, and delivery dates are not yet confirmed. Joining records your interest; it does not book fuel or lock a price.</p></div></section>
      <section className="how-section wrap" id="how-it-works"><div className="section-heading"><div><span className="wl-kicker">A HEAD START, EARNED</span><h2>Show up early.<br/>Bring good company.</h2></div><p>A real queue. Transparent points.<br/>Every confirmed referral counts.</p></div><div className="steps-grid"><article><div className="step-top"><Mail size={23}/><span>01</span></div><h3>Make your first move.</h3><p>Sign up and verify your email. You'll get a personal pass, a live position, and your first points.</p><span className="points-pill">+100 points</span></article><article><div className="step-top"><Users size={23}/><span>02</span></div><h3>Build your circle.</h3><p>Share your unique link. Each new person who verifies through it earns you referral points.</p><span className="points-pill">+50 per verified referral</span></article><article><div className="step-top"><Layers3 size={23}/><span>03</span></div><h3>Move up the list.</h3><p>More points mean a higher position. Equal points go to the earlier signup. Your pass keeps score.</p><a href="#signup" className="inline-link">Find your place <ArrowUpRight size={16}/></a></article></div></section>
      <section className="faq-section wrap"><div><span className="wl-kicker">BEFORE YOU JOIN</span><h2>A few good questions.</h2></div><div className="faq-list"><details><summary>What am I signing up for?</summary><p>An early access waitlist for deltaLP oil & gas subscriptions. Your fuel and optional region are saved after email verification. Joining does not purchase fuel, lock a price, or book delivery. Mainnet trading strategies are a separate product.</p></details><details><summary>How do positions and points work?</summary><p>A verified email earns 100 points. Each unique, verified referral earns the inviter 50. We sort by points, then original signup order. Positions can change as other people earn points. Unverified entries earn no points and are removed after 14 days.</p></details><details><summary>What does the whitelist status mean?</summary><p>Your pass starts at Waitlist. At 250 points it becomes Priority; at 600, Early circle. These are community milestones, not guaranteed admission. Launch eligibility and availability will be announced separately.</p></details><details><summary>When can I start an oil subscription?</summary><p>We are collecting fuel and region preferences to shape the pilot. Pricing, service areas, supplier coverage, and delivery terms are not confirmed. We will send updates before any subscription can be purchased.</p></details><details><summary>Does joining cost anything?</summary><p>No. This waitlist accepts no payments. Points have no cash value and do not promise fuel discounts, tokens, or an airdrop.</p></details><details><summary>Can I change devices or leave?</summary><p>Yes. Enter the same email to receive a fresh sign-in link and recover your pass. From your pass, choose Leave waitlist to delete your entry. Deleted signups also remove the referral points they earned for an inviter.</p></details></div></section>
      <section className="closing wrap"><span className="wl-mark">△</span><h2>The beginning is a good<br/>place to be.</h2><a className="wl-button" href="#signup">{member ? 'Back to your pass' : 'Get your early access pass'}<ArrowRight size={18}/></a></section>
    </main>
    <footer className="wl-footer wrap"><div><a href="/" className="wl-brand"><span className="wl-mark">△</span>delta<span>LP</span></a><p>Independent project. Not affiliated with Robinhood.</p></div><div className="footer-links"><a href="https://staccpad.fun" target="_blank" rel="noreferrer">staccpad.fun <ArrowUpRight size={14}/></a><button onClick={() => setPrivacy(true)}>Privacy & points</button><a href={source} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a><span>© {new Date().getFullYear()} deltaLP</span></div></footer>
    {!member && !sent && !verifyToken ? <a className="mobile-join" href="#signup">Join the waitlist <ArrowRight size={18}/></a> : null}
    <dialog ref={dialog} className="wl-dialog" aria-labelledby="dialog-title" onCancel={() => {setPrivacy(false);setDeleteOpen(false);}}><header><h2 id="dialog-title">{deleteOpen ? 'Leave the waitlist?' : 'Your data. Your place.'}</h2><button aria-label="Close dialog" onClick={() => {setPrivacy(false);setDeleteOpen(false);}}><X/></button></header>{deleteOpen ? <><p>This deletes your email, waitlist pass, sessions, and points. Points credited to your inviter for your signup will also be removed. This cannot be undone.</p><div className="dialog-actions"><button className="secondary-button" onClick={()=>setDeleteOpen(false)}>Keep my place</button><button className="wl-button" disabled={busy} onClick={()=>void remove()}>{busy ? 'Deleting…' : 'Delete my entry'}</button></div>{error ? <p role="alert" className="wl-error">{error}</p> : null}</> : <><p>We store your email, signup time, verification status, consent version, product preferences (including an optional region), referral attribution, and earned points to run this waitlist. Neon stores the records; Resend delivers sign-in and access emails; Vercel hosts the site.</p><p>Your email and exact position are private to your signed-in pass. Public counts include verified members only. Sign-in links expire in 20 minutes; sessions last up to 30 days.</p><p>We keep unverified entries for 14 days and verified entries until you leave or this waitlist ends. Hashed rate-limit identifiers expire after 15 minutes. Essential session cookies keep you signed in. There are no advertising trackers.</p><p>One verified email earns one signup award. Referral credit is given once per verified signup; repeat sign-ins earn nothing. Points sort the queue and have no cash value. Neither points nor tiers guarantee whitelist admission, returns, tokens, or an airdrop.</p><p>To remove your data, sign in and choose Leave waitlist. You can also raise a general issue on <a href={source+'/issues'} target="_blank" rel="noreferrer">GitHub</a>; don't post personal information there.</p></>}</dialog>
  </div>;
}
